### ISSUE TITLE
Allow not strict types

### ISSUE THREAD

**Issue by K4liber** [startable/pdtable#138]
Creating a `TableDataFrame` object we are not allowed to have a values with a different type than the unit of a column. Using the dynamic templates we are not able to create a template  `TableDataFrame` and then in another place in the code update those values based on  `TableDataFrame` object from different file.  

In the `startables` lib we have a `evaluate_expressions` mechanism. With a strict types requirement of `pdtable` loading we cannot reflect this mechanism.

**Comment by guilhermebs** [comment]
Closed by #139
