### ISSUE TITLE
Apply custom styles when writing to Excel workbook

### ISSUE THREAD

**Issue by jfcorbett** [startable/pdtable#96]
`write_excel()` currently supports a `style` bool parameter, which can be set to `True` to apply a few default, hard-coded font and background colors to table blocks in the output Excel workbook. 

Let's expand this, such that `style` also can accept a detailed style specification. This could be in the form of a JSON-like dict, JSON string, CSS... and/or even a `Table` (the bootstrapping is appealing). 

For example, a rough sketch of a JSON-like dict could be:
```
style={
    "table_name": {
        "font": {"color": "#12f400", "bold": True},   # hex color code
        "background": (212, 212, 212), ...},  # rgb color code
    "destinations": {...}, 
    ...}
```

The `table_name` dict would describe what style to apply to the table name row. (Currently, for example, the default is a blueish bold font with a certain gray background.) Same idea for `destinations`, for the destination row. All in all there would be five top-level keys:

 - `table_name`
 - `destinations`
 - `column_names`
 - `column_units`
 - `values`

I think those five together cover all the parts of a table block. Maybe add a sixth: `num_blank_lines_between_tables` (though find a nicer, shorter name) 

A style specification described thusly would be used on all the table blocks written by a given call of `write_excel()`.

**Comment by jfcorbett** [comment]
FYI @vegatheil @catcaf

**Comment by vegatheil** [comment]
A few questions:
* What are the `table_name` and `destinations` keys for in the example style dictionary?
* Are you suggesting that the `style` could be different for the different tables?

**Comment by jfcorbett** [comment]
The `table_name` dict would describe what style to apply to the table name row. (Currently, for example, it's a blueish bold font with a certain gray background.) Same idea for `destinations`, for the destination row. All in all there would be five top-level keys:

 - `table_name`
 - `destinations`
 - `column_names`
 - `column_units`
 - `values`

I think those five together cover all the parts of a table block.

**Comment by jfcorbett** [comment]
Makes sense. Should fit the columns. 

(I'm thinking, not necessarily the table name or destinations, since there's nothing tot he right of those, so they're always visible regardless of column width.)

**Comment by jfcorbett** [comment]
Text horizontal alignment is another one to look at cf. #97
